import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../opening-bell/google-apps-script.gs',import.meta.url),'utf8');
function backend(){const context=vm.createContext({console,Date,JSON});vm.runInContext(source,context);vm.runInContext(`json_=o=>o;formatDate_=()=> '2026-09-03';verifyFirebaseUser_=()=>null;findOpeningBell_=()=>({code:'TEST',endsAt:Date.now()+60000,title:'Prompt',className:'Personal Finance',block:'1',question:'Why?',sheetName:'Session'});`,context);return context}
test('manual names are required and multi-part first names stay intact',()=>{const c=backend();const identity=c.resolveOpeningBellIdentity_({manualEntry:'1',firstName:'Mary Ann',lastName:'Smith'});assert.equal(identity.firstName,'Mary Ann');assert.equal(c.rosterIdentity_(null,identity).first,'Mary Ann');assert.equal(c.resolveOpeningBellIdentity_({manualEntry:'1',firstName:'Mary'}),null)});
test('different manual students save independently; retry never appends twice',()=>{const c=backend(),rows=[['headers']],sessionRows=[];const sheet={getDataRange:()=>({getValues:()=>rows}),appendRow:r=>rows.push(r)};c.openingBellSubmissions_=()=>sheet;const ss={getSheetByName:()=>({appendRow:r=>sessionRows.push(r)})};
 for(const firstName of ['Jordan','Alex']){const identity=c.resolveOpeningBellIdentity_({manualEntry:'1',firstName,lastName:'Student'});assert.equal(c.openingBellSubmit_(ss,{code:'TEST',answer:'A complete answer'},identity).success,true)}
 assert.equal(rows.length,3);assert.equal(sessionRows.length,2);const identity=c.resolveOpeningBellIdentity_({manualEntry:'1',firstName:'Jordan',lastName:'Student'});assert.equal(c.openingBellSubmit_(ss,{code:'TEST',answer:'A complete answer'},identity).alreadySubmitted,true);assert.equal(rows.length,3);
});
test('teacher actions still require the teacher passcode',()=>{const c=backend();c.validOpeningBellTeacherPasscode_=()=>false;assert.equal(c.handleOpeningBell_({}, {},'openingBellStart').success,false);assert.equal(c.handleOpeningBell_({}, {},'openingBellTeacherAuth').success,false)});
test('opening bell source uses typed names and has valid JavaScript',()=>{const html=fs.readFileSync(new URL('../opening-bell/index.html',import.meta.url),'utf8');assert.doesNotMatch(html,/firebase|signInWithPopup|id="loginBtn"/i);assert.match(html,/manualEntry:'1',firstName,lastName/);assert.match(html,/id="firstName"/);for(const s of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(s[1]);});
