const S=window.STOCK_LAB_SETTINGS,I=window.STOCK_LAB_INDUSTRIES,REQUIRED_I=I.filter(i=>!i.optional),KEY="mrdhqStockLabV1",HISTORY_KEY="mrdhqStockLabHistoryV1",MARKET_KEY="mrdhqStockLabMarketSnapshotV1";let state=JSON.parse(localStorage.getItem(KEY)||'{"holdings":{},"journal":[],"profile":null}'),auth=null,db=null,user=null,teacher=false,currentIndustry=null,marketPrices={},marketMeta={source:"Classroom fallback",asOf:null};
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n),priceFor=c=>marketPrices[c.ticker]?.price||c.seedPrice,holdingPrice=h=>marketPrices[h.ticker]?.price||h.price,toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
function portfolioValue(){let total=0;I.forEach(i=>{const h=state.holdings[i.id];if(h)total+=h.shares*holdingPrice(h);else if(!i.optional)total+=S.allocationPerIndustry});return total}
function saveSnapshot(){if(!state.profile)return;let h=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]"),day=new Date().toISOString().slice(0,10),value=portfolioValue();if(h[h.length-1]?.day===day)h[h.length-1].value=value;else h.push({day,value});h=h.slice(-120);localStorage.setItem(HISTORY_KEY,JSON.stringify(h));state.history=h}
function save(){saveSnapshot();localStorage.setItem(KEY,JSON.stringify(state));if(user&&db)db.collection("stockLabUsers").doc(user.uid).set({name:state.profile?.name||user.displayName,email:user.email||"",className:state.profile?.className||"",teacherId:state.profile?.teacherId||"",holdings:state.holdings,journal:state.journal,onboardingPassed:!!state.onboardingPassed,quizResult:state.quizResult||null,history:state.history||[],updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}).catch(e=>console.warn("Stock Lab sync:",e))}
function calc(){let total=0,filled=0;I.forEach(i=>{const h=state.holdings[i.id];if(h){if(!i.optional)filled++;total+=h.shares*holdingPrice(h)}else if(!i.optional)total+=S.allocationPerIndustry});$("totalValue").textContent=money(total);const diff=total-S.startingCapital;$("totalReturn").textContent=money(diff)+" · "+(diff/S.startingCapital*100).toFixed(2)+"%";$("filledCount").textContent=filled+" / "+REQUIRED_I.length;$("decisionCount").textContent=state.journal.length}
function render(){renderMarketWatch();renderHistory();const g=$("industryGrid");g.innerHTML=I.map(i=>{const h=state.holdings[i.id];return '<article class="industry-card"><div class="industry-top"><div><p class="eyebrow">'+i.name+'</p><h3>'+(h?h.name:"Choose your company")+'</h3><span class="allocation">'+money(S.allocationPerIndustry)+' industry allocation</span></div><button class="'+(h?"secondary":"primary")+'" data-pick="'+i.id+'">'+(h?"SWAP STOCK":"CHOOSE")+'</button></div>'+(h?'<div class="holding"><div><strong>'+h.ticker+'</strong><small>'+h.shares.toFixed(4)+' fractional shares @ '+money(h.price)+'</small></div><b>'+money(h.shares*holdingPrice(h))+'</b></div>':'<div class="holding"><small>No holding yet. Research one of '+i.companies.length+' companies.</small></div>')+'</article>'}).join("");g.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>openPicker(b.dataset.pick));renderResearch();renderJournal();calc()}
function renderResearch(){$("researchGrid").innerHTML=I.map(i=>'<article class="research-industry"><p class="eyebrow">'+i.name+'</p><h3>Company choices</h3>'+i.companies.map(c=>{const m=marketPrices[c.ticker]||{},chg=Number(m.changePercent||0);return '<div class="company-row"><div><strong>'+c.name+'</strong><small>'+c.ticker+' · '+i.name+'</small></div><span>'+money(priceFor(c))+' <small class="'+(chg>=0?'gain':'loss')+'">'+(chg>=0?'+':'')+chg.toFixed(2)+'%</small></span><button class="secondary" data-passport="'+c.ticker+'">Passport</button></div><div class="passport hidden" id="passport-'+c.ticker+'"><div class="passport-grid"><div><span>Company</span><strong>'+c.name+'</strong></div><div><span>Ticker</span><strong>'+c.ticker+'</strong></div><div><span>Industry</span><strong>'+i.name+'</strong></div><div><span>Previous close</span><strong>'+money(priceFor(c))+'</strong></div><div><span>Daily move</span><strong>'+(chg>=0?'+':'')+chg.toFixed(2)+'%</strong></div><div><span>Research question</span><strong>How does it make money?</strong></div></div><button class="primary" data-rpick="'+i.id+'" style="margin-top:10px">Compare / Choose</button></div>'}).join("")+'</article>').join("");document.querySelectorAll("[data-passport]").forEach(b=>b.onclick=()=>document.getElementById("passport-"+b.dataset.passport).classList.toggle("hidden"));document.querySelectorAll("[data-rpick]").forEach(b=>b.onclick=()=>openPicker(b.dataset.rpick))}
function renderMarketWatch(){if(!$("moversList"))return;let rows=[];I.forEach(i=>i.companies.forEach(c=>{const m=marketPrices[c.ticker];if(m?.price)rows.push({ticker:c.ticker,name:c.name,industry:i.name,change:Number(m.changePercent||0)})}));const row=x=>'<div class="watch-row"><div><strong>'+x.ticker+' · '+x.name+'</strong><small>'+x.industry+'</small></div><b class="'+(x.change>=0?'gain':'loss')+'">'+(x.change>=0?'+':'')+x.change.toFixed(2)+'%</b></div>';$("moversList").innerHTML=rows.slice().sort((a,b)=>b.change-a.change).slice(0,7).map(row).join("")||"Market snapshot pending.";$("dropsList").innerHTML=rows.slice().sort((a,b)=>a.change-b.change).slice(0,7).map(row).join("")||"Market snapshot pending.";$("industryMoves").innerHTML=I.map(i=>{const a=rows.filter(r=>r.industry===i.name);const avg=a.length?a.reduce((n,r)=>n+r.change,0)/a.length:0;return '<div class="watch-row"><span>'+i.name+'</span><b class="'+(avg>=0?'gain':'loss')+'">'+(avg>=0?'+':'')+avg.toFixed(2)+'%</b></div>'}).join("")}
function renderHistory(){if(!$("historyChart"))return;let h=state.history||JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");$("historyCurrent").textContent=money(portfolioValue());$("historyCount").textContent=h.length;if(!h.length){$("historyChart").innerHTML="<p>No snapshots yet. Your first saved day will appear here.</p>";return}let vals=h.map(x=>x.value),min=Math.min(...vals,S.startingCapital),max=Math.max(...vals,S.startingCapital),range=Math.max(1,max-min);$("historyChart").innerHTML=h.map(x=>'<div class="history-bar" style="height:'+(20+80*(x.value-min)/range)+'%" data-tip="'+x.day+' · '+money(x.value)+'"></div>').join("")}

function renderJournal(){const j=$("journalList");j.innerHTML=state.journal.length?state.journal.slice().reverse().map(x=>'<article><time>'+new Date(x.at).toLocaleString()+'</time><h3>'+x.action+': '+x.ticker+' · '+x.industry+'</h3><p><strong>Reason:</strong> '+x.reason+'</p>'+(x.note?'<p>'+x.note+'</p>':'')+'</article>').join(""):'<article><h3>No decisions yet.</h3><p>Your first company selections will appear here.</p></article>'}
function openPicker(id){if(window.STOCK_LAB_TRADING_ENABLED!==true){toast("Stock Lab portfolios are not open yet. Research and Market Watch remain available.");return;}const requested=I.find(x=>x.id===id);if(requested?.optional){showView("research");toast("Defense is an optional research category and does not use your $15,000 portfolio.");return}if(!state.onboardingPassed){showView("learn");toast("Complete Stock Market 101 to unlock your portfolio.");return}currentIndustry=I.find(x=>x.id===id);const old=state.holdings[id];$("modalIndustry").textContent=currentIndustry.name;$("modalTitle").textContent=old?"Swap "+old.ticker+" within this industry":"Choose your first company";$("modalCompanies").innerHTML=currentIndustry.companies.map(c=>'<div class="pick-row"><div><strong>'+c.name+' ('+c.ticker+')</strong><small>Market price: '+money(priceFor(c))+'</small></div><button class="primary" data-company="'+c.ticker+'">'+(old?"Swap":"Invest")+'</button></div>').join("");$("modalCompanies").querySelectorAll("[data-company]").forEach(b=>b.onclick=()=>choose(b.dataset.company));$("modal").classList.add("open")}
function choose(ticker){if(window.STOCK_LAB_TRADING_ENABLED!==true){toast("Portfolio trading is currently closed.");return;}const today=new Date().toISOString().slice(0,10);if(eventConfig.startDate&&today<eventConfig.startDate){toast("Trading opens "+eventConfig.startDate+". Research is available now.");return}if(eventConfig.endDate&&today>eventConfig.endDate){toast("This event ended "+eventConfig.endDate+". Portfolios are read-only.");return}if(eventConfig.freezeTrading){toast("Trading is currently frozen by your teacher.");return}const weekAgo=Date.now()-7*86400000,swaps=(state.journal||[]).filter(j=>j.action==="Swap"&&new Date(j.at).getTime()>weekAgo).length;if(state.holdings[currentIndustry?.id]&&swaps>=Number(eventConfig.swapLimit||3)){toast("Weekly swap limit reached.");return}const c=currentIndustry.companies.find(x=>x.ticker===ticker),old=state.holdings[currentIndustry.id];if(old?.ticker===ticker){toast("You already own "+ticker+".");return}let reason=prompt(old?"Why are you swapping stocks? Choose a reason: Company News, Earnings, New Product/Technology, Industry Trend, Price Movement, Other":"Why did you choose "+ticker+"? Give one short reason.");if(!reason)return;let amount=old?old.shares*holdingPrice(old):S.allocationPerIndustry,p=priceFor(c);state.holdings[currentIndustry.id]={ticker:c.ticker,name:c.name,price:p,shares:amount/p};state.journal.push({at:new Date().toISOString(),action:old?"Swap":"Initial pick",ticker:c.ticker,industry:currentIndustry.name,reason,note:old?"Moved from "+old.ticker+" to "+c.ticker:""});save();$("modal").classList.remove("open");render();toast(old?"Stock swapped inside "+currentIndustry.name+".":"First "+currentIndustry.name+" investment added.")}
const timeline=["Start with a person who has an idea for a product or service.","They build the business and try to get real customers to pay for it.","If customers keep buying, the business may need more workers, equipment, stores or technology to grow.","Growth costs money. A company can borrow money, use profits, find private investors or eventually sell ownership to the public.","When a company goes public, shares let many investors own tiny pieces of the business.","After those shares exist, investors buy and sell them from each other in the stock market.","Good results or stronger expectations can make buyers willing to pay more. Bad news or weaker expectations can make them willing to pay less.","Years later, the company may be much larger, smaller or completely different. Investing is deciding what you think the business can become—not guessing from the share price alone."];let timelineIndex=0;
const quiz=[["What does owning a stock represent?",["A small piece of ownership in a company","A loan you made to the company","A guaranteed profit from the company","A discount on the company's products"],0],["Company A trades at $100 per share and Company B at $5. What can you conclude from those prices alone?",["Company A is worth more","Company B is a bargain","Company B is worth more","You cannot tell which whole company is worth more"],3],["Why might a growing business need additional money?",["To hire, build, buy equipment or expand","Because every business must sell stock","To guarantee its stock price rises","So customers can trade its products"],0],["What is diversification trying to do?",["Own only the fastest-rising stock","Spread investments across different businesses or industries","Keep every stock at the same share price","Avoid researching individual companies"],1],["What is the main goal of this Stock Market Lab?",["Guess tomorrow's biggest winner","Learn to research, build, watch and explain investment decisions","Make real money during class","Buy the stock with the highest share price"],1],["What can cause a stock price to change?",["Only the company's current profit","Only how expensive one share already is","Buyers and sellers reacting to results, news and expectations","The company choosing a new price each morning"],2],["In this lab, where do you go to compare company choices before investing?",["Research","Decision Journal","Sign out","Teacher controls"],0],["What is a sensible beginner approach in this simulation?",["Put everything into one exciting company","Choose by stock price alone","Research choices across industries and explain decisions","Swap every time a stock has one bad day"],2]];

let teacherRows=[],eventConfig={swapLimit:3,freezeTrading:false,leaderboardEnabled:true,eventName:"Fall Stock Market Lab",startDate:"",endDate:""};
async function loadTeacherDashboard(){if(!teacher||!db)return;const snap=await db.collection("stockLabUsers").get();teacherRows=snap.docs.map(d=>({uid:d.id,...d.data()}));const allowed=(S.teachers||[]).find(t=>t.id===state.profile?.teacherId);const classes=teacher?(allowed?.classes||S.classOptions||[]):[];$("teacherClassFilter").innerHTML='<option value="">All classes</option>'+[...new Set(classes)].map(c=>'<option>'+c+'</option>').join("");const es=await db.collection("stockLabConfig").doc("currentEvent").get().catch(()=>null);if(es?.exists)eventConfig={...eventConfig,...es.data()};$("eventName").value=eventConfig.eventName||"";$("eventStart").value=eventConfig.startDate||"";$("eventEnd").value=eventConfig.endDate||"";$("swapLimit").value=eventConfig.swapLimit??3;$("freezeTrading").checked=!!eventConfig.freezeTrading;$("leaderboardEnabled").checked=eventConfig.leaderboardEnabled!==false;renderTeacherRows()}
function studentValue(r){let total=0;I.forEach(i=>{const h=r.holdings?.[i.id];if(h)total+=h.shares*(marketPrices[h.ticker]?.price||h.price);else if(!i.optional)total+=S.allocationPerIndustry});return total}
function renderTeacherRows(){if(!teacher)return;const filter=$("teacherClassFilter")?.value||"",rows=teacherRows.filter(r=>!filter||r.className===filter),n=rows.length,complete=rows.filter(r=>REQUIRED_I.every(i=>r.holdings?.[i.id])).length,passed=rows.filter(r=>r.onboardingPassed).length,dec=rows.reduce((a,r)=>a+(r.journal?.length||0),0);$("tStudents").textContent=n;$("tComplete").textContent=n?Math.round(complete/n*100)+"%":"0%";$("tPassed").textContent=n?Math.round(passed/n*100)+"%":"0%";$("tDecisions").textContent=dec;$("teacherRoster").innerHTML=rows.map(r=>{const v=studentValue(r),ret=(v-S.startingCapital)/S.startingCapital*100,last=r.updatedAt?.toDate?.();return '<tr><td><strong>'+escHtml(r.name||r.email||"Student")+'</strong></td><td>'+escHtml(r.className||"—")+'</td><td>'+(r.onboardingPassed?"Passed":"Not yet")+'</td><td>'+REQUIRED_I.filter(i=>r.holdings?.[i.id]).length+'/'+REQUIRED_I.length+'</td><td>'+money(v)+'</td><td class="'+(ret>=0?'gain':'loss')+'">'+(ret>=0?'+':'')+ret.toFixed(2)+'%</td><td>'+(r.journal?.length||0)+'</td><td>'+(last?last.toLocaleDateString():"—")+'</td></tr>'}).join("");const leaders=rows.map(r=>({name:r.name||"Student",value:studentValue(r)})).sort((a,b)=>b.value-a.value).slice(0,10);$("teacherLeaderboard").innerHTML=eventConfig.leaderboardEnabled?leaders.map((r,i)=>'<div class="leader-row"><span>'+(i+1)+'. '+escHtml(r.name)+'</span><strong>'+money(r.value)+'</strong></div>').join(""):"Leaderboard hidden for this event."}
function escHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function csvDownload(name,rows){if(!rows.length){toast("No rows to export.");return}const keys=Object.keys(rows[0]),q=v=>'"'+String(v??"").replaceAll('"','""')+'"',csv=[keys.map(q).join(","),...rows.map(r=>keys.map(k=>q(r[k])).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function saveEventControls(){if(!teacher||!db)return;eventConfig={eventName:$("eventName").value.trim()||"Stock Market Lab",startDate:$("eventStart").value||"",endDate:$("eventEnd").value||"",swapLimit:Number($("swapLimit").value||0),freezeTrading:$("freezeTrading").checked,leaderboardEnabled:$("leaderboardEnabled").checked,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{await db.collection("stockLabConfig").doc("currentEvent").set(eventConfig,{merge:true});$("eventStatus").textContent="Saved successfully.";toast("Event controls saved.");renderTeacherRows()}catch(e){console.warn("Event controls:",e);$("eventStatus").textContent="Could not save: "+(e.code||e.message||"permission error");toast("Controls were not saved. Check Firebase permissions.")}}
function showView(id){if(id==="teacher"&&!teacher)return;if(id==="teacher")loadTeacherDashboard();document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===id));$(id)?.classList.add("active");const titles={learn:"Start Here",dashboard:"My Portfolio",research:"Stock Explorer",market:"Market Watch",history:"Performance",journal:"Decision Journal",teacher:"Teacher Desk"};if($("topbarTitle"))$("topbarTitle").textContent=titles[id]||"Stock Market Lab";$("terminalSidebar")?.classList.remove("mobile-open")}
function renderTimeline(){if(!$("timelineText"))return;$("timelineText").textContent=timeline[timelineIndex];$("timelineStep").textContent=(timelineIndex+1)+" / "+timeline.length;$("timelineBack").disabled=timelineIndex===0;$("timelineNext").textContent=timelineIndex===timeline.length-1?"Start Quiz ↓":"Next →"}
function startQuiz(){
  let q=0,score=0,answers=[];const area=$("quizArea"),button=$("startQuiz");
  button.hidden=true;$("quizResult").textContent="";
  function draw(){
    if(q>=quiz.length){
      const pass=score>=6;state.quizResult={score,total:quiz.length,passed:pass,answers,completedAt:new Date().toISOString()};
      if(pass)state.onboardingPassed=true;
      save();render();
      area.innerHTML='<div class="quiz-review"><h3>'+score+' / '+quiz.length+' correct</h3><p>'+(pass?'Introduction complete. Your teacher will open portfolio selections when the lab launches.':'Review the explanations below, then retry.')+'</p>'+answers.map((a,i)=>'<div class="quiz-review-item"><strong>'+escHtml(quiz[i][0])+'</strong><p>Your answer: '+escHtml(quiz[i][1][a.selected])+'</p><p>Correct answer: '+escHtml(quiz[i][1][quiz[i][2]])+'</p></div>').join("")+'</div>';
      $("quizResult").textContent=pass?"Completed · "+score+" / "+quiz.length:"Not yet passed · "+score+" / "+quiz.length;
      button.hidden=false;button.textContent=pass?"Review / Retake Quiz":"Retry Mini Quiz";return;
    }
    const item=quiz[q];area.innerHTML='<p class="quiz-count">Question '+(q+1)+' of '+quiz.length+'</p><h3>'+escHtml(item[0])+'</h3><div class="quiz-options">'+item[1].map((x,i)=>'<button type="button" class="secondary" data-answer="'+i+'">'+escHtml(x)+'</button>').join("")+'</div><p id="answerFeedback" aria-live="polite"></p>';
    area.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{
      const selected=Number(b.dataset.answer),correct=selected===item[2];if(correct)score++;
      answers.push({selected,correct});area.querySelectorAll("[data-answer]").forEach(x=>x.disabled=true);
      b.classList.add(correct?"correct-answer":"incorrect-answer");
      area.querySelector('[data-answer="'+item[2]+'"]').classList.add("correct-answer");
      $("answerFeedback").textContent=correct?"Correct.":"The correct answer is: "+item[1][item[2]];
      const next=document.createElement("button");next.type="button";next.className="primary";next.textContent=q===quiz.length-1?"See results":"Next question →";next.onclick=()=>{q++;draw()};area.appendChild(next);
    });
  }draw();
}
function updateAccountUI(status){
 const signed=!!user, demo=!signed&&!!state.profile, name=signed?(state.profile?.name||user.displayName||"Google account"):(demo?"Demo preview":"Guest");
 const email=signed?(user.email||"Google connected"):(demo?"Preview only · not saved online":"Sign in to save your work");
 const el=id=>$(id);if(el("accountName"))el("accountName").textContent=name;
 if(el("accountEmail"))el("accountEmail").textContent=email;
 if(el("accountAvatar"))el("accountAvatar").textContent=name.trim().charAt(0).toUpperCase()||"?";
 if(el("accountState"))el("accountState").textContent=signed?"● Google connected":demo?"● Demo · local only":"● Not signed in";
 if(el("topbarAuth"))el("topbarAuth").textContent=signed?"● "+name:demo?"DEMO · NOT SYNCED":"NOT SIGNED IN";
 if(el("sidebarSignIn"))el("sidebarSignIn").hidden=signed;
 if(el("topbarSignIn"))el("topbarSignIn").hidden=signed;
 if(el("logoutBtn"))el("logoutBtn").hidden=!signed;
 if(el("navQuizStatus"))el("navQuizStatus").textContent=state.onboardingPassed?"✓":"1";
}
function beginGoogleSignIn(){if(!auth){toast("Google sign-in is still loading. Try again.");return} $("googleBtn").click()}
function profile(u){state.profile={name:u?.displayName||"Demo Student",email:u?.email||"",className:state.profile?.className||"",teacherId:state.profile?.teacherId||""};$("studentLine").textContent=state.profile.name+(state.profile.className?" · "+state.profile.className:"");$("logoutBtn").hidden=!u;teacher=!!u&&S.teacherEmails.map(x=>x.toLowerCase()).includes((u.email||"").toLowerCase());$("teacherTab").hidden=!teacher;updateAccountUI()}


function renderClassGate(){if(!user||state.profile?.className){$("classGate").classList.remove("open");return}const teachers=S.teachers||[];const mr=teachers.find(t=>t.id==="mr-d")||{id:"mr-d",name:"Mr. D",classes:S.classOptions||[]};$("mrDClasses").innerHTML=mr.classes.map(c=>'<button class="class-choice" data-teacher="'+mr.id+'" data-class="'+c+'"><strong>'+c+'</strong><span>Mr. D</span></button>').join("");$("otherTeacherClasses").innerHTML=teachers.filter(t=>t.id!=="mr-d").flatMap(t=>t.classes.map(c=>'<button class="class-choice" data-teacher="'+t.id+'" data-class="'+c+'"><strong>'+c+'</strong><span>'+t.name+'</span></button>')).join("");document.querySelectorAll(".class-choice").forEach(b=>b.onclick=async()=>{state.profile.className=b.dataset.class;state.profile.teacherId=b.dataset.teacher;save();$("classGate").classList.remove("open");profile(user);render();toast("Class saved.")});$("classGate").classList.add("open")}
function renderTicker(){const el=$("stockTicker");if(!el)return;const rows=[];I.forEach(ind=>ind.companies.forEach(c=>{const m=marketPrices[c.ticker];if(m?.price)rows.push({ticker:c.ticker,price:m.price,changePercent:Number(m.changePercent||0)})}));if(!rows.length){el.textContent="Previous-close market data is loading. Portfolio prices will update when the shared snapshot is available.";return}const items=rows.slice(0,50).map(x=>'<span class="ticker-item"><b>'+x.ticker+'</b> '+money(x.price)+' <em class="'+(x.changePercent>=0?"up":"down")+'">'+(x.changePercent>=0?"+":"")+x.changePercent.toFixed(2)+'%</em></span>').join("");el.innerHTML=items+items;$("tickerAsOf").textContent=marketMeta.asOf?"Close · "+String(marketMeta.asOf):"Latest completed close"}
function applyMarketSnapshot(data){if(!data||!data.prices)return false;const next={};Object.entries(data.prices).forEach(([ticker,v])=>{const price=Number(typeof v==="object"?v.price:v);if(price>0)next[ticker.toUpperCase()]={price,asOf:(typeof v==="object"&&v.asOf)||data.asOf||null,source:(typeof v==="object"&&v.source)||data.source||"Shared market snapshot",previousClose:Number(typeof v==="object"?v.previousClose:0)||null,change:Number(typeof v==="object"?v.change:0)||0}});if(!Object.keys(next).length)return false;marketPrices=next;Object.entries(data.prices).forEach(([ticker,v])=>{if(typeof v==="object"&&marketPrices[ticker.toUpperCase()])marketPrices[ticker.toUpperCase()].changePercent=Number(v.changePercent||0)});marketMeta={source:data.source||"Shared market snapshot",asOf:data.asOf||null};renderTicker();renderMarketWatch();renderHistory();localStorage.setItem(MARKET_KEY,JSON.stringify({prices:next,source:marketMeta.source,asOf:marketMeta.asOf,cachedAt:Date.now()}));const el=$("marketStatus");if(el)el.textContent=marketMeta.asOf?"Last market snapshot · "+new Date(marketMeta.asOf).toLocaleString():"Last market snapshot";return true}
const STOCK_LAB_FEED_URL="https://script.google.com/macros/s/AKfycbw9g6vKH9fgVjzlefmd6tywOPRek1RdHtWiZEpdiflS4sjFlR352_vz62VYBW00CNx7/exec";
let stockLabFeedPending=null;
function fetchStockLabFeed(){
  if(stockLabFeedPending)return stockLabFeedPending;
  stockLabFeedPending=new Promise((resolve,reject)=>{
    const script=document.createElement("script");
    let settled=false;
    const previous=window.stockLabReceiveMarket;
    const timer=setTimeout(()=>finish(new Error("Stock Lab feed timed out")),12000);
    function finish(error,data){
      if(settled)return;
      settled=true;clearTimeout(timer);script.remove();
      if(previous===undefined)delete window.stockLabReceiveMarket;
      else window.stockLabReceiveMarket=previous;
      error?reject(error):resolve(data);
    }
    window.stockLabReceiveMarket=data=>{
      if(!data?.success||!data?.prices||Number(data.count)<1)return finish(new Error("Invalid Stock Lab feed"));
      finish(null,data);
    };
    script.onerror=()=>finish(new Error("Stock Lab feed unavailable"));
    script.src=STOCK_LAB_FEED_URL+(STOCK_LAB_FEED_URL.includes("?")?"&":"?")+"v="+Date.now();
    document.head.appendChild(script);
  }).finally(()=>{stockLabFeedPending=null});
  return stockLabFeedPending;
}
async function loadMarketPrices(){
  // Show the last published close immediately; the dedicated Sheet feed takes precedence.
  const staticSnapshot=window.STOCK_LAB_MARKET_SNAPSHOT;
  if(staticSnapshot?.prices&&applyMarketSnapshot(staticSnapshot))render();
  else try{
    const cached=JSON.parse(localStorage.getItem(MARKET_KEY)||"null");
    if(cached?.prices&&applyMarketSnapshot(cached))render();
  }catch(e){}
  try{
    const live=await fetchStockLabFeed();
    if(applyMarketSnapshot(live)){render();return}
  }catch(e){console.warn("Stock Lab Sheet feed:",e)}
  if(!Object.keys(marketPrices).length&&db){
    try{
      const snap=await db.collection("stockLabMarket").doc("latest").get();
      if(snap.exists&&applyMarketSnapshot(snap.data()))render();
    }catch(e){console.warn("Market snapshot fallback:",e)}
  }
  if(!Object.keys(marketPrices).length){
    const el=$("marketStatus");if(el)el.textContent="Market data unavailable";
  }
}
async function initFirebase(){const cfg=window.STOCK_LAB_FIREBASE_CONFIG||{};if(!cfg.apiKey||String(cfg.apiKey).includes("REPLACE")){console.info("Stock Lab Firebase is intentionally not connected until its separate project config is supplied.");updateAccountUI();return}try{const stockApp=firebase.initializeApp(cfg,"stock-market-lab");auth=stockApp.auth();db=stockApp.firestore();await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.getRedirectResult().catch(e=>{if(e?.code)console.warn("Google redirect:",e.code)});auth.onAuthStateChanged(async u=>{user=u;if(u){const snap=await db.collection("stockLabUsers").doc(u.uid).get().catch(()=>null);if(snap?.exists){const d=snap.data();state={holdings:d.holdings||{},journal:d.journal||[],history:d.history||[],onboardingPassed:!!d.onboardingPassed,quizResult:d.quizResult||null,profile:{name:d.name||u.displayName,email:u.email,className:d.className||"",teacherId:d.teacherId||""}};localStorage.setItem(KEY,JSON.stringify(state))}else{state={holdings:{},journal:[],history:[],onboardingPassed:false,quizResult:null,profile:{name:u.displayName||"",email:u.email||"",className:"",teacherId:""}};localStorage.setItem(KEY,JSON.stringify(state));localStorage.removeItem(HISTORY_KEY);profile(u);await db.collection("stockLabUsers").doc(u.uid).set({name:u.displayName||"",email:u.email||"",className:state.profile?.className||"",teacherId:state.profile?.teacherId||"",holdings:state.holdings||{},journal:state.journal||[],history:state.history||[],onboardingPassed:!!state.onboardingPassed,quizResult:state.quizResult||null,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}profile(u);$("authGate").classList.remove("open");renderClassGate();try{const es=await db.collection("stockLabConfig").doc("currentEvent").get();if(es.exists)eventConfig={...eventConfig,...es.data()}}catch(e){}await loadMarketPrices();render();renderTicker()}else {state.profile=null;updateAccountUI();$("authGate").classList.remove("open");showView("learn")}})}catch(e){console.warn(e);updateAccountUI();toast("Google connection unavailable; research remains accessible.")}}
$("teacherClassFilter").onchange=renderTeacherRows;$("refreshTeacher").onclick=loadTeacherDashboard;$("saveEvent").onclick=saveEventControls;$("exportStudents").onclick=()=>csvDownload("stock-lab-students.csv",teacherRows.map(r=>({name:r.name,email:r.email,class:r.className,teacher:r.teacherId,onboarding:r.onboardingPassed?"Passed":"Not yet",industries:Object.keys(r.holdings||{}).length,value:studentValue(r).toFixed(2),decisions:r.journal?.length||0})));$("exportTransactions").onclick=()=>csvDownload("stock-lab-decisions.csv",teacherRows.flatMap(r=>(r.journal||[]).map(j=>({student:r.name,email:r.email,class:r.className,date:j.at,action:j.action,ticker:j.ticker,industry:j.industry,reason:j.reason,note:j.note||""}))));
document.querySelectorAll("nav [data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));$("timelineBack").onclick=()=>{timelineIndex=Math.max(0,timelineIndex-1);renderTimeline()};$("timelineNext").onclick=()=>{if(timelineIndex<timeline.length-1){timelineIndex++;renderTimeline()}else startQuiz()};$("startQuiz").onclick=startQuiz;renderTimeline();$("closeModal").onclick=()=>$("modal").classList.remove("open");$("modal").onclick=e=>{if(e.target.id==="modal")$("modal").classList.remove("open")};$("sidebarSignIn").onclick=beginGoogleSignIn;$("topbarSignIn").onclick=beginGoogleSignIn;$("mobileMenu").onclick=()=>$("terminalSidebar").classList.toggle("mobile-open");$("googleBtn").onclick=async()=>{if(!auth){toast("Google sign-in is still loading. Try again.");return}const p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:"select_account"});try{await auth.signInWithPopup(p)}catch(e){console.warn("Google sign-in:",e);const code=e?.code||"";if(code==="auth/unauthorized-domain")toast("Google login setup needs MRDHQ authorized in Firebase.");else if(code==="auth/popup-blocked")toast("Allow the Google sign-in window, then try again.");else if(code==="auth/popup-closed-by-user"||code==="auth/cancelled-popup-request")toast("Google sign-in window was closed.");else if(code==="auth/operation-not-allowed")toast("Google sign-in must be enabled in Firebase.");else toast("Google sign-in error: "+(code.replace("auth/","")||"please try again."))}};$("otherTeacherBtn").onclick=()=>{$("otherTeacherPanel").hidden=!$("otherTeacherPanel").hidden};$("demoBtn").onclick=()=>{state.profile={name:"Demo Student",className:"Business 101",teacherId:"mr-d"};profile(null);$("authGate").classList.remove("open");save();render()};$("logoutBtn").onclick=()=>auth?.signOut().then(()=>{state.profile=null;localStorage.removeItem(KEY);location.reload()});render();showView("learn");updateAccountUI();loadMarketPrices();initFirebase();