window.STOCK_LAB_INDUSTRIES=[
{id:"technology",name:"Technology & AI",companies:[["AAPL","Apple",230],["MSFT","Microsoft",515],["NVDA","NVIDIA",175],["AMD","AMD",160],["DELL","Dell",135],["INTC","Intel",35],["ADBE","Adobe",355],["CRM","Salesforce",245],["GOOGL","Alphabet",350],["META","Meta Platforms",665],["AVGO","Broadcom",358],["ORCL","Oracle",148],["MU","Micron",160],["PLTR","Palantir",178],["SMCI","Super Micro Computer",39],["CSCO","Cisco",110]]},
{id:"retail",name:"Retail & Shopping",companies:[["AMZN","Amazon",230],["WMT","Walmart",105],["TGT","Target",95],["COST","Costco",950],["HD","Home Depot",410],["LOW","Lowe's",255],["BBY","Best Buy",75],["EBAY","eBay",90]]},
{id:"transport",name:"Cars & Transportation",companies:[["TSLA","Tesla",430],["F","Ford",12],["GM","General Motors",58],["TM","Toyota",205],["UBER","Uber",95],["LYFT","Lyft",18],["DAL","Delta Air Lines",62],["LUV","Southwest Airlines",42],["AAL","American Airlines",13],["UPS","UPS",95]]},
{id:"food",name:"Food & Restaurants",companies:[["KO","Coca-Cola",70],["PEP","PepsiCo",150],["MCD","McDonald's",305],["SBUX","Starbucks",90],["CMG","Chipotle",42],["DPZ","Domino's",445],["YUM","Yum! Brands",155],["MNST","Monster Beverage",66]]},
{id:"media",name:"Entertainment & Media",companies:[["DIS","Disney",115],["NFLX","Netflix",95],["SPOT","Spotify",710],["EA","Electronic Arts",175],["TTWO","Take-Two Interactive",250],["CMCSA","Comcast",35],["WBD","Warner Bros. Discovery",18],["RBLX","Roblox",130]]},
{id:"finance",name:"Banking & Money",companies:[["JPM","JPMorgan Chase",310],["BAC","Bank of America",52],["COF","Capital One",220],["V","Visa",350],["MA","Mastercard",590],["AXP","American Express",350],["PYPL","PayPal",70],["HOOD","Robinhood",120],["SOFI","SoFi",17],["COIN","Coinbase",300],["XYZ","Block",75]]},
{id:"health",name:"Healthcare",companies:[["LLY","Eli Lilly",760],["PFE","Pfizer",25],["JNJ","Johnson & Johnson",180],["CVS","CVS Health",78],["UNH","UnitedHealth",350],["ABT","Abbott",130],["MRK","Merck",85],["HCA","HCA Healthcare",430]]},
{id:"energy",name:"Energy & Industry",companies:[["XOM","ExxonMobil",120],["CVX","Chevron",160],["COP","ConocoPhillips",100],["CAT","Caterpillar",475],["DE","Deere",510],["GE","GE Aerospace",290],["NEE","NextEra Energy",80],["DUK","Duke Energy",125]]},
{id:"brands",name:"Clothing, Sports & Brands",companies:[["NKE","Nike",70],["LULU","Lululemon",190],["RL","Ralph Lauren",330],["DECK","Deckers Outdoor",105],["UAA","Under Armour",6],["LEVI","Levi Strauss",23],["CROX","Crocs",85],["COLM","Columbia Sportswear",55]]},
{id:"housing",name:"Building, Housing & Real Estate",companies:[["Z","Zillow",85],["DHI","D.R. Horton",175],["LEN","Lennar",130],["PHM","PulteGroup",135],["O","Realty Income",60],["PLD","Prologis",125],["SHW","Sherwin-Williams",355],["BLDR","Builders FirstSource",130]]}
].map(i=>({...i,companies:i.companies.map(c=>({ticker:c[0],name:c[1],seedPrice:c[2]}))}));