window.STOCK_LAB_INDUSTRIES=[
{id:"technology",name:"Technology & AI",companies:[["AAPL","Apple",230],["MSFT","Microsoft",515],["NVDA","NVIDIA",175],["AMD","AMD",160],["DELL","Dell",135],["INTC","Intel",35],["ADBE","Adobe",355],["CRM","Salesforce",245],["GOOGL","Alphabet",350],["META","Meta Platforms",665],["AVGO","Broadcom",358],["ORCL","Oracle",148],["MU","Micron",160],["PLTR","Palantir",178],["SMCI","Super Micro Computer",39],["CSCO","Cisco",110],["QCOM","Qualcomm",175],["IBM","IBM",250],["NOW","ServiceNow",900],["SNOW","Snowflake",200],["TSM","TSMC",300],["SNDK","Sandisk",150],["WDC","Western Digital",120],["STX","Seagate",250],["MRVL","Marvell Technology",90],["LRCX","Lam Research",160],["AMAT","Applied Materials",220],["APP","AppLovin",600],["VRT","Vertiv",180],["ANET","Arista Networks",150],["CRWD","CrowdStrike",500],["PANW","Palo Alto Networks",220]]},
{id:"retail",name:"Retail & Shopping",companies:[["AMZN","Amazon",230],["WMT","Walmart",105],["TGT","Target",95],["COST","Costco",950],["HD","Home Depot",410],["LOW","Lowe's",255],["BBY","Best Buy",75],["EBAY","eBay",90],["ETSY","Etsy",60],["CHWY","Chewy",40],["BABA","Alibaba",150],["MELI","MercadoLibre",2000],["ROST","Ross Stores",160],["TJX","TJX Companies",150]]},
{id:"transport",name:"Cars & Transportation",companies:[["TSLA","Tesla",430],["F","Ford",12],["GM","General Motors",58],["TM","Toyota",205],["UBER","Uber",95],["LYFT","Lyft",18],["DAL","Delta Air Lines",62],["LUV","Southwest Airlines",42],["AAL","American Airlines",13],["UPS","UPS",95],["RIVN","Rivian",15],["LCID","Lucid",3],["RACE","Ferrari",500],["NIO","NIO",6],["FDX","FedEx",300],["CVNA","Carvana",350]]},
{id:"food",name:"Food & Restaurants",companies:[["KO","Coca-Cola",70],["PEP","PepsiCo",150],["MCD","McDonald's",305],["SBUX","Starbucks",90],["CMG","Chipotle",42],["DPZ","Domino's",445],["YUM","Yum! Brands",155],["MNST","Monster Beverage",66],["CAVA","Cava",80],["SHAK","Shake Shack",100],["DASH","DoorDash",250],["KDP","Keurig Dr Pepper",35],["MDLZ","Mondelez",65],["HSY","Hershey",190],["CELH","Celsius",55],["BROS","Dutch Bros",65],["TSN","Tyson Foods",60],["GIS","General Mills",55],["KHC","Kraft Heinz",25],["CPB","Campbell's",35],["CAG","Conagra Brands",20],["WING","Wingstop",300],["TXRH","Texas Roadhouse",180],["QSR","Restaurant Brands International",70]]},
{id:"media",name:"Entertainment & Media",companies:[["DIS","Disney",115],["NFLX","Netflix",95],["SPOT","Spotify",710],["EA","Electronic Arts",175],["TTWO","Take-Two Interactive",250],["CMCSA","Comcast",35],["WBD","Warner Bros. Discovery",18],["RBLX","Roblox",130],["PARA","Paramount",15],["ROKU","Roku",90],["SNAP","Snap",10],["PINS","Pinterest",35],["RDDT","Reddit",200],["TKO","TKO Group",180],["APP","AppLovin",600]]},
{id:"finance",name:"Banking & Money",companies:[["JPM","JPMorgan Chase",310],["BAC","Bank of America",52],["COF","Capital One",220],["V","Visa",350],["MA","Mastercard",590],["AXP","American Express",350],["PYPL","PayPal",70],["HOOD","Robinhood",120],["SOFI","SoFi",17],["COIN","Coinbase",300],["XYZ","Block",75],["GS","Goldman Sachs",800],["MS","Morgan Stanley",160],["SCHW","Charles Schwab",100],["C","Citigroup",100],["AFRM","Affirm",70]]},
{id:"health",name:"Healthcare",companies:[["LLY","Eli Lilly",760],["PFE","Pfizer",25],["JNJ","Johnson & Johnson",180],["CVS","CVS Health",78],["UNH","UnitedHealth",350],["ABT","Abbott",130],["MRK","Merck",85],["HCA","HCA Healthcare",430],["TMO","Thermo Fisher",500],["ISRG","Intuitive Surgical",500],["MDT","Medtronic",100],["GILD","Gilead Sciences",120],["VRTX","Vertex Pharmaceuticals",450],["MCK","McKesson",800],["MRNA","Moderna",100]]},
{id:"energy",name:"Energy & Industry",companies:[["XOM","ExxonMobil",120],["CVX","Chevron",160],["COP","ConocoPhillips",100],["CAT","Caterpillar",475],["DE","Deere",510],["GE","GE Aerospace",290],["NEE","NextEra Energy",80],["DUK","Duke Energy",125],["SLB","SLB",50],["FSLR","First Solar",250],["CEG","Constellation Energy",350],["VST","Vistra",200],["ETN","Eaton",400],["HON","Honeywell",250],["GEV","GE Vernova",700],["MPC","Marathon Petroleum",200],["VLO","Valero Energy",180],["PWR","Quanta Services",500]]},
{id:"brands",name:"Clothing, Sports & Brands",companies:[["NKE","Nike",70],["LULU","Lululemon",190],["RL","Ralph Lauren",330],["DECK","Deckers Outdoor",105],["UAA","Under Armour",6],["LEVI","Levi Strauss",23],["CROX","Crocs",85],["COLM","Columbia Sportswear",55],["ONON","On Holding",50],["VFC","VF Corporation",20],["PVH","PVH",100],["SKX","Skechers",65],["TPR","Tapestry",100],["VSTO","Vista Outdoor",40],["CELH","Celsius",55]]},
{id:"housing",name:"Building, Housing & Real Estate",companies:[["Z","Zillow",85],["DHI","D.R. Horton",175],["LEN","Lennar",130],["PHM","PulteGroup",135],["O","Realty Income",60],["PLD","Prologis",125],["SHW","Sherwin-Williams",355],["BLDR","Builders FirstSource",130],["LOW","Lowe's",255],["HD","Home Depot",410],["CBRE","CBRE Group",160],["AMT","American Tower",220],["SPG","Simon Property Group",180],["WY","Weyerhaeuser",30]]},
{id:"defense",name:"Defense, Aerospace & Security",companies:[["LMT","Lockheed Martin",500],["RTX","RTX",170],["NOC","Northrop Grumman",600],["GD","General Dynamics",350],["LHX","L3Harris",300],["HII","Huntington Ingalls",300],["BA","Boeing",220],["HWM","Howmet Aerospace",200],["AVAV","AeroVironment",300],["AXON","Axon Enterprise",700],["PLTR","Palantir",178],["GE","GE Aerospace",290],["HON","Honeywell",250]]}
].map(i=>({...i,companies:i.companies.map(c=>({ticker:c[0],name:c[1],seedPrice:c[2]}))}));