/* Market News Desk: source-linked RSS, with explicit fetch failures. */
(function(){
const $=id=>document.getElementById(id), esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const all=[...new Map(I.flatMap(i=>i.companies.map(c=>[c.ticker,c]))).values()];
const select=$("newsTicker");if(!select)return;
select.innerHTML='<option value="">All companies</option>'+all.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>'<option value="'+esc(c.ticker)+'">'+esc(c.name)+' ('+esc(c.ticker)+')</option>').join("");
const cache=new Map();let request=0;
const feed=q=>'https://news.google.com/rss/search?q='+encodeURIComponent(q)+'&hl=en-US&gl=US&ceid=US:en';
function movers(){return all.map(c=>({c,m:marketPrices[c.ticker]})).filter(x=>Number.isFinite(Number(x.m?.changePercent))&&x.m?.price>0).sort((a,b)=>Math.abs(b.m.changePercent)-Math.abs(a.m.changePercent)).slice(0,8)}
function query(){
const ticker=select.value,topic=$("newsTopic").value;
if(ticker){const c=all.find(x=>x.ticker===ticker);return '"'+c.name+'" '+ticker+' stock when:7d'}
if(topic==="portfolio"){const held=Object.values(state.holdings||{}).slice(0,6);return held.length?held.map(h=>'"'+h.name+'"').join(' OR ')+' stock when:7d':'stock market company earnings when:2d'}
if(topic==="movers"){const top=movers().slice(0,5);return top.length?top.map(x=>'"'+x.c.name+'"').join(' OR ')+' stock when:2d':'stock market movers when:2d'}
return {market:'stock market business companies when:2d',technology:'artificial intelligence semiconductor cloud companies when:3d',earnings:'company earnings revenue quarterly results when:3d'}[topic];
}
function strip(){const rows=movers();$("newsMoverStrip").innerHTML=rows.length?rows.map(x=>'<button type="button" class="secondary" data-news-ticker="'+esc(x.c.ticker)+'">'+esc(x.c.ticker)+' · '+(x.m.changePercent>=0?'+':'')+Number(x.m.changePercent).toFixed(2)+'%</button>').join(''):'<p>Latest completed market snapshot is not available yet.</p>'}
function parse(xml){const doc=new DOMParser().parseFromString(xml,'text/xml');if(doc.querySelector('parsererror'))throw Error('Invalid RSS response');return [...doc.querySelectorAll('item')].slice(0,24).map(item=>({title:item.querySelector('title')?.textContent||'',link:item.querySelector('link')?.textContent||'',date:item.querySelector('pubDate')?.textContent||'',source:item.querySelector('source')?.textContent||'Google News'})).filter(x=>x.title&&/^https:\/\//.test(x.link))}
async function fetchFeed(url){if(cache.has(url)&&Date.now()-cache.get(url).at<300000)return cache.get(url).items;const endpoints=['https://api.allorigins.win/raw?url='+encodeURIComponent(url),'https://api.rss2json.com/v1/api.json?rss_url='+encodeURIComponent(url)];let error;for(const endpoint of endpoints){try{const response=await fetch(endpoint,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Feed service '+response.status);const body=await response.text();let items;if(body.trim().startsWith('{')){const json=JSON.parse(body);if(json.status!=='ok')throw Error(json.message||'Feed unavailable');items=(json.items||[]).slice(0,24).map(x=>({title:x.title,link:x.link,date:x.pubDate,source:json.feed?.title||'RSS'})).filter(x=>/^https:\/\//.test(x.link))}else items=parse(body);if(!items.length)throw Error('No recent articles');cache.set(url,{at:Date.now(),items});return items}catch(e){error=e}}throw error||Error('RSS unavailable')}
async function load(force=false){const id=++request;strip();const url=feed(query());if(force)cache.delete(url);$("newsStatus").textContent='Loading source headlines…';$("newsArticles").innerHTML='';try{const items=await fetchFeed(url);if(id!==request)return;$("newsStatus").textContent=items.length+' articles · RSS · refreshed '+new Date().toLocaleTimeString();$("newsArticles").innerHTML=items.map(x=>'<article class="stock-card"><p class="eyebrow">'+esc(x.source)+' · '+esc(x.date?new Date(x.date).toLocaleDateString():'Date unavailable')+'</p><h3>'+esc(x.title)+'</h3><a class="secondary" style="display:inline-block;text-decoration:none" href="'+esc(x.link)+'" target="_blank" rel="noopener noreferrer">Read article ↗</a></article>').join('')}catch(e){if(id!==request)return;$("newsStatus").textContent='Live feed unavailable';$("newsArticles").innerHTML='<article class="stock-card"><h3>Headlines could not load</h3><p>The RSS service may be unavailable or limiting requests. Open the original feed to see its current headlines.</p><a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">Open source RSS ↗</a></article>'}}
$("newsTopic").onchange=()=>{select.value='';load()};select.onchange=()=>load();$("newsRefresh").onclick=()=>load(true);$("newsMoverStrip").onclick=e=>{const b=e.target.closest('[data-news-ticker]');if(b){select.value=b.dataset.newsTicker;load()}};window.STOCK_LAB_LOAD_NEWS=()=>load();
})();