/**
 * CASHS Student Store API — Cloudflare Worker + D1.
 * Bind STORE_DB (D1), TEACHER_PASSWORD (secret), and LUNCH_PEPPER (secret).
 * Route: mrdhq.com/api/student-store*
 * Apply db/schema.sql before turning on student attendance.
 * Do not commit student lunch numbers or teacher secrets to Git.
 */
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
const fail=(error,status=400)=>json({ok:false,error},status);
function equal(a,b){a=String(a||"");b=String(b||"");let x=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)x|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return x===0}
async function digest(secret,value){const bytes=new TextEncoder().encode(secret+":"+value);return [...new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))].map(v=>v.toString(16).padStart(2,"0")).join("")}
function ny(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function now(){return new Date().toISOString()}
async function throttle(db,kind,ip,max=8){const bucket=Math.floor(Date.now()/900000);const key=kind+":"+ip+":"+bucket;await db.prepare("INSERT INTO rate_limits (key,attempts) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET attempts=attempts+1").bind(key).run();const r=await db.prepare("SELECT attempts FROM rate_limits WHERE key=?").bind(key).first();return r.attempts<=max}
async function schedule(db){const employees=(await db.prepare("SELECT id,name FROM employees WHERE active=1 ORDER BY name").all()).results;const shifts=(await db.prepare("SELECT s.id,s.employee_id,s.shift_date AS date,s.day_type AS dayType,s.start_time AS start,s.end_time AS end,s.role,s.duties,e.name FROM shifts s JOIN employees e ON e.id=s.employee_id WHERE s.shift_date>=date('now','-7 days') AND s.shift_date<=date('now','+60 days') AND e.active=1 ORDER BY s.shift_date,s.start_time,e.name").all()).results;return {ok:true,employees,shifts}}
async function action(request,env){if(!env.STORE_DB||!env.TEACHER_PASSWORD||!env.LUNCH_PEPPER)return fail("Store backend setup incomplete.",503);
const url=new URL(request.url);if(request.method==="GET"&&url.searchParams.get("action")==="schedule")return json(await schedule(env.STORE_DB));
if(request.method!=="POST")return fail("Unsupported request.",405);
if(Number(request.headers.get("content-length")||0)>12000)return fail("Request too large.",413);
let data;try{data=await request.json()}catch{return fail("Invalid JSON.")}if(!data||typeof data!=="object")return fail("Invalid request.");
const ip=request.headers.get("CF-Connecting-IP")||"unknown";const db=env.STORE_DB;
const teacherActions=["teacher-check","add-employee","add-shift","attendance"];
if(teacherActions.includes(data.action)){if(!await throttle(db,"teacher",ip,15))return fail("Too many attempts; try again later.",429);if(!equal(request.headers.get("X-Store-Teacher"),env.TEACHER_PASSWORD))return fail("Teacher access denied.",403)}
if(data.action==="teacher-check")return json({ok:true});
if(data.action==="add-employee"){const name=String(data.name||"").trim(),pin=String(data.lunchNumber||"").trim();if(name.length<2||name.length>90||!/^[0-9]{3,12}$/.test(pin))return fail("Enter a name and valid numeric lunch number.");const hash=await digest(env.LUNCH_PEPPER,pin);try{await db.prepare("INSERT INTO employees (name,lunch_hash) VALUES (?,?)").bind(name,hash).run();return json({ok:true})}catch{return fail("Employee could not be added. This lunch number may already be registered.",409)}}
if(data.action==="add-shift"){const employeeId=Number(data.employeeId),date=String(data.date||""),day=String(data.dayType||""),start=String(data.start||""),end=String(data.end||""),role=String(data.role||"").trim(),duties=String(data.duties||"").trim();if(!Number.isSafeInteger(employeeId)||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!["A","B","Other"].includes(day)||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end)||start>=end||role.length<3||role.length>100||duties.length<3||duties.length>1200)return fail("Check employee, date, times, role and duties. End must follow start.");const e=await db.prepare("SELECT id FROM employees WHERE id=? AND active=1").bind(employeeId).first();if(!e)return fail("Employee not found.");await db.prepare("INSERT INTO shifts (employee_id,shift_date,day_type,start_time,end_time,role,duties) VALUES (?,?,?,?,?,?,?)").bind(employeeId,date,day,start,end,role,duties).run();return json({ok:true})}
if(data.action==="attendance"){const rows=(await db.prepare("SELECT a.id,e.name,a.in_at AS inAt,a.out_at AS outAt,CASE WHEN a.out_at IS NULL THEN NULL ELSE CAST((julianday(a.out_at)-julianday(a.in_at))*1440 AS INTEGER) END AS minutes FROM attendance a JOIN employees e ON e.id=a.employee_id ORDER BY a.in_at DESC LIMIT 250").all()).results;return json({ok:true,records:rows})}
if(data.action==="punch"){if(!await throttle(db,"punch",ip,20))return fail("Too many attempts. Ask Mr. D for assistance.",429);const pin=String(data.lunchNumber||"").trim();if(!/^[0-9]{3,12}$/.test(pin)||!["in","out"].includes(data.direction))return fail("Enter your lunch number and choose Sign In or Sign Out.");const hash=await digest(env.LUNCH_PEPPER,pin);const e=await db.prepare("SELECT id,name FROM employees WHERE lunch_hash=? AND active=1").bind(hash).first();if(!e)return fail("Lunch number not recognized. Ask Mr. D to confirm your roster entry.",403);
const active=await db.prepare("SELECT id FROM attendance WHERE employee_id=? AND out_at IS NULL ORDER BY id DESC LIMIT 1").bind(e.id).first();
if(data.direction==="in"){if(active)return fail("You are already signed in. Use Sign Out when your shift ends.",409);const shift=await db.prepare("SELECT id FROM shifts WHERE employee_id=? AND shift_date=? LIMIT 1").bind(e.id,ny()).first();if(!shift)return fail("No shift is scheduled for you today. Ask Mr. D to add or correct the schedule.",409);await db.prepare("INSERT INTO attendance (employee_id,shift_id,in_at) VALUES (?,?,?)").bind(e.id,shift.id,now()).run();return json({ok:true,message:e.name+": sign-in recorded by the server."})}
if(!active)return fail("No active sign-in found. Ask Mr. D for assistance.",409);await db.prepare("UPDATE attendance SET out_at=? WHERE id=? AND out_at IS NULL").bind(now(),active.id).run();return json({ok:true,message:e.name+": sign-out recorded by the server."})}
return fail("Unknown action.",404)}
export default {async fetch(request,env){try{const url=new URL(request.url);if(!url.pathname.startsWith("/api/student-store"))return fail("Not found.",404);return await action(request,env)}catch(e){console.error("Store API error",e);return fail("Store service error. Please contact Mr. D.",500)}}};
