/**
 * CASHS Student Store API — Cloudflare Worker + D1.
 * Bind STORE_DB (D1), TEACHER_PASSWORD (secret), and LUNCH_PEPPER (secret).
 * Route: mrdhq.com/api/student-store*
 * Apply db/schema.sql before turning on student attendance.
 * Do not commit student lunch numbers or teacher secrets to Git.
 */
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
const fail=(error,status=400)=>json({ok:false,error},status);
function equal(a,b){a=String(a||"");b=String(b||"");let x=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)x|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return x===0}
async function digest(secret,value){const bytes=new TextEncoder().encode(secret+":"+value);return [...new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))].map(v=>v.toString(16).padStart(2,"0")).join("")}
function ny(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function now(){return new Date().toISOString()}
async function throttle(db,kind,ip,max=8){const bucket=Math.floor(Date.now()/900000);const key=kind+":"+ip+":"+bucket;await db.prepare("INSERT INTO rate_limits (key,attempts) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET attempts=attempts+1").bind(key).run();const r=await db.prepare("SELECT attempts FROM rate_limits WHERE key=?").bind(key).first();return r.attempts<=max}
async function schedule(db){const employees=(await db.prepare("SELECT id,name FROM employees WHERE active=1 ORDER BY name").all()).results;const shifts=(await db.prepare("SELECT s.id,s.employee_id,s.shift_date AS date,s.day_type AS dayType,s.start_time AS start,s.end_time AS end,s.lunch_period AS lunchPeriod,s.role,s.duty_a AS dutyA,s.duty_b AS dutyB,s.duty_c AS dutyC,e.name FROM shifts s JOIN employees e ON e.id=s.employee_id WHERE s.shift_date>=date('now','-7 days') AND s.shift_date<=date('now','+60 days') AND e.active=1 ORDER BY s.shift_date,s.start_time,e.name").all()).results;return {ok:true,employees,shifts}}

async function student(db,env,pin){if(!/^[0-9]{3,12}$/.test(String(pin||"")))return null;return await db.prepare("SELECT id,name FROM employees WHERE lunch_hash=? AND active=1").bind(await digest(env.LUNCH_PEPPER,String(pin).trim())).first()}
function code(){const a=new Uint8Array(24);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,"0")).join("")}
function validEmail(email){return email.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)}
async function action(request,env){if(!env.STORE_DB||!env.TEACHER_PASSWORD||!env.LUNCH_PEPPER)return fail("Store backend setup incomplete.",503);
const url=new URL(request.url);if(request.method==="GET"&&url.searchParams.get("action")==="schedule")return json(await schedule(env.STORE_DB));
if(request.method!=="POST")return fail("Unsupported request.",405);
if(Number(request.headers.get("content-length")||0)>12000)return fail("Request too large.",413);
let data;try{data=await request.json()}catch{return fail("Invalid JSON.")}if(!data||typeof data!=="object")return fail("Invalid request.");
const ip=request.headers.get("CF-Connecting-IP")||"unknown";const db=env.STORE_DB;
const teacherActions=["teacher-check","add-employee","add-shift","attendance","guardian-list","teacher-notes","teacher-reply"];
if(teacherActions.includes(data.action)){if(!await throttle(db,"teacher",ip,15))return fail("Too many attempts; try again later.",429);if(!equal(request.headers.get("X-Store-Teacher"),env.TEACHER_PASSWORD))return fail("Teacher access denied.",403)}
if(data.action==="teacher-check")return json({ok:true});
if(data.action==="add-employee"){const name=String(data.name||"").trim(),pin=String(data.lunchNumber||"").trim(),parentName=String(data.parentName||"").trim(),parentEmail=String(data.parentEmail||"").trim();if(name.length<2||name.length>90||!/^[0-9]{3,12}$/.test(pin)||(parentEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(parentEmail))||parentName.length>100||parentEmail.length>254)return fail("Enter a name and valid numeric lunch number.");const hash=await digest(env.LUNCH_PEPPER,pin);try{await db.prepare("INSERT INTO employees (name,lunch_hash,parent_name,parent_email) VALUES (?,?,?,?)").bind(name,hash,parentName||null,parentEmail||null).run();return json({ok:true})}catch{return fail("Employee could not be added. This lunch number may already be registered.",409)}}
if(data.action==="add-shift"){const employeeId=Number(data.employeeId),date=String(data.date||""),day=String(data.dayType||""),lunch=String(data.lunchPeriod||""),start=String(data.start||""),end=String(data.end||""),role=String(data.role||"").trim(),a=String(data.dutyA||"").trim(),b=String(data.dutyB||"").trim(),c=String(data.dutyC||"").trim();if(!Number.isSafeInteger(employeeId)||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!["A","B"].includes(day)||!["A","B","C",""].includes(lunch)||String(data.block)!=="3"||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end)||start>=end||role.length<3||role.length>100||![a,b,c].every(x=>x.length>=3&&x.length<=600))return fail("Check A/B day, Block 3, shift times, role and all three duties.");const e=await db.prepare("SELECT id FROM employees WHERE id=? AND active=1").bind(employeeId).first();if(!e)return fail("Employee not found.");await db.prepare("INSERT INTO shifts (employee_id,shift_date,day_type,block,lunch_period,start_time,end_time,role,duties,duty_a,duty_b,duty_c) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(employeeId,date,day,3,lunch,start,end,role,[a,b,c].join("; "),a,b,c).run();return json({ok:true})}
if(data.action==="attendance"){const rows=(await db.prepare("SELECT a.id,e.name,a.in_at AS inAt,a.out_at AS outAt,CASE WHEN a.out_at IS NULL THEN NULL ELSE CAST((julianday(a.out_at)-julianday(a.in_at))*1440 AS INTEGER) END AS minutes FROM attendance a JOIN employees e ON e.id=a.employee_id ORDER BY a.in_at DESC LIMIT 250").all()).results;return json({ok:true,records:rows})}

if(data.action==="guardian-contact"){if(!await throttle(db,"guardian",ip,8))return fail("Too many submissions.",429);
const e=await student(db,env,data.lunchNumber),parentName=String(data.parentName||"").trim(),parentEmail=String(data.parentEmail||"").trim().toLowerCase(),studentSignature=String(data.studentSignature||"").trim(),parentSignature=String(data.parentSignature||"").trim();
if(!e)return fail("Lunch number not recognized.",403);
if(!validEmail(parentEmail)||parentName.length<2||parentName.length>100||studentSignature.toLowerCase()!==e.name.toLowerCase()||parentSignature.toLowerCase()!==parentName.toLowerCase()||data.studentAgrees!=="on"||data.parentAgrees!=="on")return fail("Check both signatures, names, email, and acknowledgments.");
const stamped=now();await db.prepare("UPDATE employees SET parent_name=?,parent_email=? WHERE id=?").bind(parentName,parentEmail,e.id).run();
await db.prepare("INSERT INTO informal_agreements(employee_id,student_signature,parent_signature,parent_name,parent_email,student_signed_at,parent_signed_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(employee_id) DO UPDATE SET student_signature=excluded.student_signature,parent_signature=excluded.parent_signature,parent_name=excluded.parent_name,parent_email=excluded.parent_email,student_signed_at=excluded.student_signed_at,parent_signed_at=excluded.parent_signed_at").bind(e.id,studentSignature,parentSignature,parentName,parentEmail,stamped,stamped).run();
return json({ok:true,createdAt:stamped})}
if(data.action==="guardian-list"){const contacts=(await db.prepare("SELECT e.id,e.name,e.parent_name AS parentName,e.parent_email AS parentEmail,a.student_signed_at AS studentSignedAt,a.parent_signed_at AS parentSignedAt FROM employees e LEFT JOIN informal_agreements a ON a.employee_id=e.id WHERE e.active=1 ORDER BY e.name").all()).results;return json({ok:true,contacts})}
if(data.action==="new-note"){if(!await throttle(db,"note",ip,8))return fail("Too many notes.",429);const e=await student(db,env,data.lunchNumber),name=String(data.name||"").trim(),topic=String(data.topic||""),message=String(data.message||"").trim();if(!e)return fail("Lunch number not recognized.",403);if(name.toLowerCase()!==e.name.toLowerCase())return fail("Name does not match the roster.",403);if(!["Question","Schedule","Task update","Supplies / Inventory","Concern","Other"].includes(topic)||message.length<3||message.length>2500)return fail("Check topic and message.");const token=code(),hash=await digest(env.LUNCH_PEPPER,token),created=now();const result=await db.prepare("INSERT INTO notes (employee_id,topic,token_hash,created_at) VALUES (?,?,?,?)").bind(e.id,topic,hash,created).run();await db.prepare("INSERT INTO note_messages (note_id,author,message,created_at) VALUES (?,?,?,?)").bind(result.meta.last_row_id,e.name,message,created).run();return json({ok:true,code:token,createdAt:created})}
if(data.action==="get-thread"||data.action==="student-reply"){if(!await throttle(db,"discussion",ip,20))return fail("Too many attempts.",429);const token=String(data.code||"").trim();if(!/^[a-f0-9]{48}$/.test(token))return fail("Invalid discussion code.",403);const note=await db.prepare("SELECT id FROM notes WHERE token_hash=?").bind(await digest(env.LUNCH_PEPPER,token)).first();if(!note)return fail("Discussion not found.",404);if(data.action==="student-reply"){const message=String(data.message||"").trim();if(message.length<3||message.length>2500)return fail("Message must be 3–2500 characters.");await db.prepare("INSERT INTO note_messages (note_id,author,message,created_at) VALUES (?,?,?,?)").bind(note.id,"Student",message,now()).run()}const messages=(await db.prepare("SELECT author,message,created_at AS createdAt FROM note_messages WHERE note_id=? ORDER BY id").bind(note.id).all()).results;return json({ok:true,messages})}
if(data.action==="teacher-notes"){const notes=(await db.prepare("SELECT n.id,e.name,n.topic,n.created_at AS createdAt,(SELECT m.message FROM note_messages m WHERE m.note_id=n.id ORDER BY m.id DESC LIMIT 1) AS latestMessage FROM notes n JOIN employees e ON e.id=n.employee_id ORDER BY n.created_at DESC LIMIT 200").all()).results;return json({ok:true,notes})}
if(data.action==="teacher-reply"){const id=Number(data.noteId),message=String(data.message||"").trim();if(!Number.isSafeInteger(id)||message.length<3||message.length>2500)return fail("Invalid note or reply.");const n=await db.prepare("SELECT id FROM notes WHERE id=?").bind(id).first();if(!n)return fail("Discussion not found.",404);await db.prepare("INSERT INTO note_messages (note_id,author,message,created_at) VALUES (?,?,?,?)").bind(id,"Mr. D",message,now()).run();return json({ok:true})}
if(data.action==="punch"){if(!await throttle(db,"punch",ip,20))return fail("Too many attempts. Ask Mr. D for assistance.",429);const pin=String(data.lunchNumber||"").trim();if(!/^[0-9]{3,12}$/.test(pin)||!["in","out"].includes(data.direction))return fail("Enter your lunch number and choose Sign In or Sign Out.");const hash=await digest(env.LUNCH_PEPPER,pin);const e=await db.prepare("SELECT id,name FROM employees WHERE lunch_hash=? AND active=1").bind(hash).first();if(!e)return fail("Lunch number not recognized. Ask Mr. D to confirm your roster entry.",403);
const active=await db.prepare("SELECT id FROM attendance WHERE employee_id=? AND out_at IS NULL ORDER BY id DESC LIMIT 1").bind(e.id).first();
if(data.direction==="in"){if(active)return fail("You are already signed in. Use Sign Out when your shift ends.",409);const shift=await db.prepare("SELECT id FROM shifts WHERE employee_id=? AND shift_date=? LIMIT 1").bind(e.id,ny()).first();if(!shift)return fail("No shift is scheduled for you today. Ask Mr. D to add or correct the schedule.",409);await db.prepare("INSERT INTO attendance (employee_id,shift_id,in_at) VALUES (?,?,?)").bind(e.id,shift.id,now()).run();return json({ok:true,message:e.name+": sign-in recorded by the server."})}
if(!active)return fail("No active sign-in found. Ask Mr. D for assistance.",409);await db.prepare("UPDATE attendance SET out_at=? WHERE id=? AND out_at IS NULL").bind(now(),active.id).run();return json({ok:true,message:e.name+": sign-out recorded by the server."})}
return fail("Unknown action.",404)}
export default {async fetch(request,env){try{const url=new URL(request.url);if(!url.pathname.startsWith("/api/student-store"))return fail("Not found.",404);return await action(request,env)}catch(e){console.error("Store API error",e);return fail("Store service error. Please contact Mr. D.",500)}}};
